services:
  - type: web
    name: tineal-hub
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: PAYSTACK_SRC_KEY
        sync: false
      - key: ARKESEL_API_KEY
        sync: false
      - key: ARKESEL_SENDER_ID
        value: TINEAL
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587